name: Question
description: Ask a question about yt-dlp usage
labels: [question]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: |
        Carefully read and work through this check list in order to prevent the most common mistakes and misuse of yt-dlp:
      options:
        - label: I'm asking a genuine question about yt-dlp and not requesting support for a specific site
          required: true
        - label: I've read the [README](https://github.com/yt-dlp/yt-dlp/blob/master/README.md) and [FAQ](https://github.com/yt-dlp/yt-dlp/wiki/FAQ)
          required: true
        - label: I've searched the [existing issues](https://github.com/yt-dlp/yt-dlp/issues) and the [discussions](https://github.com/yt-dlp/yt-dlp/discussions) for similar questions
          required: true

  - type: textarea
    id: question
    attributes:
      label: Question
      description: Ask your question here. Be as specific as possible.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples that might help answer your question.
    validations:
      required: false
